# Generated by Django 2.2.3 on 2019-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_str', models.TextField()),
                ('upload_date', models.DateTimeField(verbose_name='date published')),
                ('is_deal', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
